"""
Interactive helper to create/update .env quickly.
"""

from __future__ import annotations

from pathlib import Path


ENV_PATH = Path(".env")

FIELDS = [
    ("APP_ENV", "App environment (dev/prod)", "dev"),
    ("APP_HOST", "API bind host", "0.0.0.0"),
    ("APP_PORT", "API port", "8000"),
    ("AI_PROVIDER", "Primary AI provider (ollama/gemini)", "ollama"),
    ("FALLBACK_PROVIDER", "Fallback AI provider (gemini/ollama)", "gemini"),
    ("ENABLE_FALLBACK", "Enable fallback true/false", "true"),
    ("PARSER_MODE", "Parser mode (hybrid/llm)", "hybrid"),
    ("OLLAMA_MODEL", "Ollama model", "llama3.2:latest"),
    ("OLLAMA_URL", "Ollama URL", "http://127.0.0.1:11434/api/generate"),
    ("GEMINI_MODEL", "Gemini model", "gemini-2.0-flash"),
    ("GEMINI_API_KEY", "Gemini API key", ""),
    ("OPENAI_API_KEY", "OpenAI API key (optional)", ""),
    ("WHISPER_MODEL", "Whisper/STT model", "gpt-4o-mini-transcribe"),
    ("WHATSAPP_VERIFY_TOKEN", "WhatsApp webhook verify token", ""),
    ("WHATSAPP_ACCESS_TOKEN", "WhatsApp Cloud API access token", ""),
    ("WHATSAPP_PHONE_NUMBER_ID", "WhatsApp phone number id", ""),
    ("WHATSAPP_BUSINESS_ACCOUNT_ID", "WhatsApp business account id", ""),
    ("WHATSAPP_GRAPH_VERSION", "WhatsApp Graph API version", "v21.0"),
    ("WHATSAPP_API_BASE", "WhatsApp API base", "https://graph.facebook.com"),
    ("OWNER_WHATSAPP_NUMBER", "Owner WhatsApp number (E.164)", ""),
    ("CUSTOMER_PHONEBOOK", "JSON map: {\"Raju\":\"+91...\"}", ""),
    ("REMINDER_RUN_TIME", "Reminder run time (HH:MM)", "10:00"),
    ("REMINDER_MIN_DAYS", "Reminder min pending days", "15"),
    ("REMINDER_MIN_AMOUNT", "Reminder min amount", "500"),
    ("DEFAULT_COUNTRY_CODE", "Default country code", "+91"),
    ("KWIKKHATA_ENABLE_BACKUP", "Enable backup true/false", "true"),
    ("KWIKKHATA_BACKUP_DIR", "Backup directory", "backups"),
    ("KWIKKHATA_BACKUP_KEEP", "How many backups to keep", "20"),
]


def load_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def prompt_value(key: str, label: str, current: str, default: str) -> str:
    shown_default = current if current != "" else default
    prompt = f"{label} [{shown_default}]: "
    entered = input(prompt).strip()
    if entered:
        return entered
    if current != "":
        return current
    return default


def write_env(path: Path, values: dict[str, str]) -> None:
    ordered_keys = [key for key, _, _ in FIELDS]
    lines = [
        "# Auto-generated by scripts/env_wizard.py",
        "# Safe to edit manually.",
        "",
    ]
    for key in ordered_keys:
        lines.append(f"{key}={values.get(key, '')}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    print("KwikKhata .env wizard\nPress Enter to keep existing/default value.\n")
    existing = load_env(ENV_PATH)
    updated: dict[str, str] = {}

    for key, label, default in FIELDS:
        current = existing.get(key, "")
        updated[key] = prompt_value(key, label, current, default)

    write_env(ENV_PATH, updated)
    print(f"\nDone. Updated {ENV_PATH.resolve()}")


if __name__ == "__main__":
    main()
